apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-swarm-checkpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinite-swarm-checkpoint
  template:
    metadata:
      labels:
        app: infinite-swarm-checkpoint
    spec:
      containers:
      - name: infinite-swarm-checkpoint
        image: Agentcygroup/infinite-swarm-checkpoint:latest
        ports:
        - containerPort: 8000
